# Generated by Django 4.0.5 on 2022-06-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDate',
            fields=[
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('last_update_time', models.DateTimeField(auto_now=True, help_text='修改时间')),
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('in_time', models.DateTimeField()),
                ('out_time', models.DateTimeField()),
                ('state', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_time'],
                'abstract': False,
            },
        ),
    ]
